version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smartprintai-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: smartprint
      POSTGRES_PASSWORD: fd86e47ea9fa864b3867a19e164882c31398c14d3cb2a816
      POSTGRES_DB: smartprintai
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - smartprintai_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: smartprintai-redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6380:6379"
    volumes:
      - smartprintai_redis:/data

  minio:
    image: minio/minio
    container_name: smartprintai-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: spaib7cc0dbf
      MINIO_ROOT_PASSWORD: f9e0d2b2fed5e7a6f8276c77f43db17792c23b250d7f656f
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - smartprintai_minio:/data

volumes:
  smartprintai_pgdata:
  smartprintai_redis:
  smartprintai_minio:
