import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const PRODUCTS = [
    {
        name: 'Unisex T-Shirt',
        printfulId: '71',
        description: 'Classic unisex tee, comfortable everyday wear. 100% cotton.',
        category: 'apparel',
        basePrice: 11.50,
        sellPrice: 29.99,
        sizes: ['S', 'M', 'L', 'XL', '2XL'],
        colors: [
            { name: 'White', hex: '#FFFFFF', printfulVariantId: 4012 },
            { name: 'Black', hex: '#1A1A1A', printfulVariantId: 4013 },
            { name: 'Navy', hex: '#1B2A4A', printfulVariantId: 4014 },
        ],
        imageUrl: '/products/tshirt.jpg',
        printArea: { width: 4200, height: 4800, dpi: 300 },
    },
    {
        name: 'Premium Hoodie',
        printfulId: '380',
        description: 'Heavyweight premium hoodie. Soft fleece lining, kangaroo pocket.',
        category: 'apparel',
        basePrice: 26.00,
        sellPrice: 59.99,
        sizes: ['S', 'M', 'L', 'XL', '2XL'],
        colors: [
            { name: 'White', hex: '#FFFFFF', printfulVariantId: 13440 },
            { name: 'Black', hex: '#1A1A1A', printfulVariantId: 13441 },
        ],
        imageUrl: '/products/hoodie.jpg',
        printArea: { width: 4200, height: 4800, dpi: 300 },
    },
    {
        name: 'White Mug 11oz',
        printfulId: '19',
        description: 'Classic ceramic mug. Microwave and dishwasher safe.',
        category: 'drinkware',
        basePrice: 5.95,
        sellPrice: 18.99,
        sizes: ['11oz'],
        colors: [{ name: 'White', hex: '#FFFFFF', printfulVariantId: 1320 }],
        imageUrl: '/products/mug.jpg',
        printArea: { width: 2700, height: 1350, dpi: 300 },
    },
    {
        name: 'Phone Case',
        printfulId: '175',
        description: 'Slim-fit phone case with matte finish.',
        category: 'accessories',
        basePrice: 9.00,
        sellPrice: 24.99,
        sizes: ['iPhone 14', 'iPhone 15', 'iPhone 15 Pro', 'Samsung S24'],
        colors: [{ name: 'Clear', hex: '#F0F0F0', printfulVariantId: 10835 }],
        imageUrl: '/products/phonecase.jpg',
        printArea: { width: 1800, height: 3000, dpi: 300 },
    },
    {
        name: 'Canvas Print 12×12',
        printfulId: '1',
        description: 'Gallery-quality canvas print on wooden frame.',
        category: 'wall-art',
        basePrice: 13.50,
        sellPrice: 39.99,
        sizes: ['12x12'],
        colors: [{ name: 'White', hex: '#FFFFFF', printfulVariantId: 1 }],
        imageUrl: '/products/canvas.jpg',
        printArea: { width: 3600, height: 3600, dpi: 300 },
    },
    {
        name: 'Tote Bag',
        printfulId: '83',
        description: 'Eco-friendly cotton tote bag.',
        category: 'accessories',
        basePrice: 8.50,
        sellPrice: 22.99,
        sizes: ['One Size'],
        colors: [
            { name: 'Natural', hex: '#F5F0E8', printfulVariantId: 4710 },
            { name: 'Black', hex: '#1A1A1A', printfulVariantId: 4711 },
        ],
        imageUrl: '/products/tote.jpg',
        printArea: { width: 3600, height: 3600, dpi: 300 },
    },
    {
        name: 'Sweatshirt',
        printfulId: '262',
        description: 'Soft crewneck sweatshirt for all seasons.',
        category: 'apparel',
        basePrice: 20.00,
        sellPrice: 49.99,
        sizes: ['S', 'M', 'L', 'XL', '2XL'],
        colors: [
            { name: 'White', hex: '#FFFFFF', printfulVariantId: 8700 },
            { name: 'Black', hex: '#1A1A1A', printfulVariantId: 8701 },
        ],
        imageUrl: '/products/sweatshirt.jpg',
        printArea: { width: 4200, height: 4800, dpi: 300 },
    },
    {
        name: 'Pillow 18×18',
        printfulId: '3',
        description: 'Custom throw pillow with soft filling.',
        category: 'home',
        basePrice: 12.00,
        sellPrice: 34.99,
        sizes: ['18x18'],
        colors: [{ name: 'White', hex: '#FFFFFF', printfulVariantId: 2 }],
        imageUrl: '/products/pillow.jpg',
        printArea: { width: 4050, height: 4050, dpi: 300 },
    },
    {
        name: 'Framed Poster',
        printfulId: '2',
        description: 'Museum-quality framed poster with clean modern frame.',
        category: 'wall-art',
        basePrice: 14.00,
        sellPrice: 44.99,
        sizes: ['12x18', '18x24'],
        colors: [{ name: 'White Frame', hex: '#FFFFFF', printfulVariantId: 3 }],
        imageUrl: '/products/poster.jpg',
        printArea: { width: 3600, height: 5400, dpi: 300 },
    },
    {
        name: 'Sticker Sheet',
        printfulId: '358',
        description: 'Kiss-cut vinyl stickers on a sheet.',
        category: 'accessories',
        basePrice: 4.00,
        sellPrice: 12.99,
        sizes: ['4x4', '3x3'],
        colors: [{ name: 'White', hex: '#FFFFFF', printfulVariantId: 12600 }],
        imageUrl: '/products/stickers.jpg',
        printArea: { width: 1200, height: 1200, dpi: 300 },
    },
    {
        name: 'Baseball Cap',
        printfulId: '206',
        description: 'Structured baseball cap with embroidered front.',
        category: 'apparel',
        basePrice: 11.00,
        sellPrice: 29.99,
        sizes: ['One Size'],
        colors: [
            { name: 'White', hex: '#FFFFFF', printfulVariantId: 7854 },
            { name: 'Black', hex: '#1A1A1A', printfulVariantId: 7855 },
        ],
        imageUrl: '/products/cap.jpg',
        printArea: { width: 2400, height: 2400, dpi: 300 },
    },
    {
        name: 'Kids T-Shirt',
        printfulId: '305',
        description: 'Soft cotton tee for kids. Fun and durable.',
        category: 'apparel',
        basePrice: 9.00,
        sellPrice: 24.99,
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: [
            { name: 'White', hex: '#FFFFFF', printfulVariantId: 11050 },
            { name: 'Black', hex: '#1A1A1A', printfulVariantId: 11051 },
        ],
        imageUrl: '/products/kids-tshirt.jpg',
        printArea: { width: 3600, height: 4200, dpi: 300 },
    },
    {
        name: 'Notebook',
        printfulId: '473',
        description: 'Hardcover lined notebook with custom cover.',
        category: 'accessories',
        basePrice: 10.00,
        sellPrice: 27.99,
        sizes: ['5.5x8.5'],
        colors: [{ name: 'White', hex: '#FFFFFF', printfulVariantId: 15400 }],
        imageUrl: '/products/notebook.jpg',
        printArea: { width: 3300, height: 5100, dpi: 300 },
    },
    {
        name: 'Tank Top',
        printfulId: '163',
        description: 'Lightweight unisex tank top for summer.',
        category: 'apparel',
        basePrice: 9.50,
        sellPrice: 24.99,
        sizes: ['S', 'M', 'L', 'XL', '2XL'],
        colors: [
            { name: 'White', hex: '#FFFFFF', printfulVariantId: 7900 },
            { name: 'Black', hex: '#1A1A1A', printfulVariantId: 7901 },
        ],
        imageUrl: '/products/tanktop.jpg',
        printArea: { width: 3600, height: 4200, dpi: 300 },
    },
    {
        name: 'Fleece Blanket',
        printfulId: '327',
        description: 'Ultra-soft fleece blanket for cozy nights.',
        category: 'home',
        basePrice: 25.00,
        sellPrice: 64.99,
        sizes: ['50x60'],
        colors: [{ name: 'White', hex: '#FFFFFF', printfulVariantId: 12000 }],
        imageUrl: '/products/blanket.jpg',
        printArea: { width: 6000, height: 7200, dpi: 300 },
    },
]

async function main() {
    console.log('🌱 Seeding products...')

    for (const product of PRODUCTS) {
        await prisma.product.upsert({
            where: { printfulId: product.printfulId },
            update: product,
            create: product,
        })
    }

    console.log(`✅ Seeded ${PRODUCTS.length} products`)
}

main()
    .catch(console.error)
    .finally(() => prisma.$disconnect())
